version: '3.8'

services:
  main-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true
  main-github-test:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./test-deploy:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main-build
    profiles:
      - github-test